"""Initial migration

Revision ID: 1c1007618e58
Revises: 
Create Date: 2025-06-06 17:10:56.738223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1007618e58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('price_discounted', sa.Float(), nullable=True),
    sa.Column('price_original', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('number_of_reviews', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('characteristics', sa.Text(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('configurations',
    sa.Column('conf_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motherboard_id', sa.Integer(), nullable=True),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('cpu_id', sa.Integer(), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('cooler_id', sa.Integer(), nullable=True),
    sa.Column('ram_id', sa.Integer(), nullable=True),
    sa.Column('hdd_id', sa.Integer(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cooler_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['cpu_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['frame_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['hdd_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['motherboard_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['unified_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conf_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    op.drop_table('users')
    op.drop_table('unified_products')
    # ### end Alembic commands ###
